name: 🐛 Bug Report
description: Report a bug or issue with SUCA
title: "🐛 [Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 👋 Thanks for taking the time to report a bug!
        
        Please fill out this template to help us understand and reproduce the issue.
        The more detailed information you provide, the faster we can fix it! 🚀

  - type: checkboxes
    id: checklist
    attributes:
      label: 📋 Pre-submission Checklist
      description: Please verify these before submitting
      options:
        - label: I searched existing issues and didn't find a duplicate
          required: true
        - label: I'm using the latest version of SUCA
          required: true
        - label: I can reproduce this issue consistently
          required: true

  - type: textarea
    id: description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Steps to Reproduce
      description: Step-by-step instructions to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 🖥️ Platform
      description: Which platform are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Web Browser
    validations:
      required: true

  - type: dropdown
    id: version-type
    attributes:
      label: 📦 Version Type
      description: Which version of SUCA are you using?
      options:
        - Portable (Recommended)
        - Installer
        - Web Version
        - Development Build
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 📋 Version
      description: What version of SUCA are you running?
      placeholder: "v0.1.0"
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: 🖥️ Operating System Version
      description: Your OS version
      placeholder: "Windows 11, macOS Sonoma 14.0, Ubuntu 22.04, etc."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🔥 Severity
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality but has workaround
        - High - Blocks major functionality
        - Critical - App crashes or data loss
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🎯 Component
      description: Which component is affected?
      options:
        - IPv4 Calculator
        - IPv6 Calculator
        - Subnet Division
        - Cryptography Tools
        - Network Tools
        - UI/Theme
        - Window/Electron
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots/Videos
      description: Add screenshots or videos to help explain the problem
      placeholder: Drag and drop images here or paste URLs...

  - type: textarea
    id: console-logs
    attributes:
      label: 🔍 Console Logs/Error Messages
      description: Any relevant console logs or error messages
      placeholder: Paste console output or error messages here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Any other context about the problem
      placeholder: Add any other relevant information...

  - type: checkboxes
    id: impact
    attributes:
      label: 📊 Impact Assessment
      description: Check all that apply
      options:
        - label: This affects my primary workflow
        - label: This prevents me from using a core feature
        - label: This causes data loss or corruption
        - label: This affects multiple users (if known)
        - label: This is a regression from a previous version

  - type: textarea
    id: workaround
    attributes:
      label: 🔧 Workaround (if any)
      description: Have you found any temporary workaround?
      placeholder: Describe any workaround you've found...

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 🙏 Thank you for your contribution!
        
        Your bug report helps make SUCA better for everyone. We'll review this as soon as possible!
        
        📧 Need immediate help? Check our [documentation](https://github.com/yourusername/suca/wiki) or [discussions](https://github.com/yourusername/suca/discussions) 